class ApiConstants{
  static const baseUrl = 'https://etms.com.sg:';
  static const login = 'loginuser';
  static const getAttendance = 'getAttendance';
  static const getLeaveType = 'getEmpLeaveType';
  static const getLeaveReportList = 'getLeaveList';
  static const getDates = 'getdates';
  static const getDatesDetail = 'getdates_001';
  static const getLeaveCarry = 'getLeavecarry';
  static const getLeaveStatusDetail = 'getLeaveStatusDetail';
  static const getLeaveStatusFirst = 'getLeaveStatusFirstApproval';
  static const getLeaveStatusSecond = 'getLeaveStatusSecondApproval';
  static const getAttSumary = 'getAttendance_Summary';
  static const getPayrollPayPeriod = 'getPayrollPayPeriod';
  static const getPayrollDetail = 'getPayrollPayslipMain';
  static const getPayslipAllowance = 'getPayrollPayslipAllowan';
  static const getPayslipDeduction = 'getPayrollPayslipDeduction';
  static const getLeaveDates = 'getdates';
  static const getMyPhoto = 'getMyPhoto';
  static const getEmpMaster = 'EmpMaster';
  static const getRelationTypes = 'RelationType';
  static const getMaritalStatus = 'MaritalStatus';
  static const getCountries = 'Countries';
  static const getNextKin = 'EmpNextofKin';
  static const upload = 'upload';
  static const resetPassword = 'resetPassword';
  static const getGeneralSetting = 'getGeneralSetting?KeyWord=CheckInType';
  static const getQRCode = 'getQRCode';
  static const getLeaveStatusFirstApproval_001= 'getLeaveStatusFirstApproval_001';
  static const getLeaveStatusSecondApproval_001 = 'getLeaveStatusSecondApproval_001';
  static const getLeaveStatusDetail_001 = 'getLeaveStatusDetail_001';
  static const applyAttendance = 'MB_Att_Approval_Det';
  static const saveLeaveApplication = 'LeaveApplication';
  static const saveLeavePhoto = 'saveMcSlip';
}